// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetUserPackages(arg1:Array<string>,arg2:string):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;
