// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCommunities() {
  return window['go']['backend']['App']['GetCommunities']();
}

export function GetUserPackages(arg1, arg2) {
  return window['go']['backend']['App']['GetUserPackages'](arg1, arg2);
}
