// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {experimental} from '../models';

export function GetCommunities():Promise<experimental.CommunityList>;

export function GetUserPackages(arg1:Array<string>,arg2:string):Promise<string>;
