// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserPackages(arg1, arg2) {
  return window['go']['backend']['App']['GetUserPackages'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}
