name: Crossplatform Build
on: 
  # Require workflow to be manually triggered.
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options: 
          - info
          - warning
          - debug

env:
  # Necessary for most environments as build failure can occur due to OOM issues.
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Windows'
            platform:  'windows/amd64'
            os: 'windows-latest'

          - name: 'Linux'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          
          - name: 'MacOS'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Wails Build
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22.1'