name: Crossplatform Build
on: 
  # Allows workflow to be manually triggered.
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        type: choice
        options: [info, warning, debug]
        default: "warning"
      nsis:
        description: "Create installer"
        type: boolean
        required: true
      package: 
        description: "Upload artifacts"
        type: boolean
        required: false
        default: true

env:
  # Necessary for most environments as build failure can occur due to OOM issues.
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: "modm8.exe", platform: "windows/amd64", os: "windows-latest" },
          { name: "modm8", platform: "linux/amd64", os: "ubuntu-latest" },
          { name: "modm8", platform: "linux/arm64", os: "ubuntu-latest" },
          # { name: "modm8", platform: "darwin/universal", os: "macos-latest" }
        ]

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Wails Build
        uses: The-Egg-Corp/wails-build-action@main
        id: build
        with:
          name: "modm8"
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          nsis: ${{ inputs.nsis }}
          package: ${{ inputs.package }}
          go-version: '1.23'
          node-version: 20
          setup-bun: true
