name: Crossplatform Build
on: 
  # Require workflow to be manually triggered.
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options: 
          - info
          - warning
          - debug

env:
  # Necessary for most environments as build failure can occur due to OOM issues.
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: 'modm8', platform: 'linux/amd64', os: 'ubuntu-latest' },
          { name: 'modm8', platform: 'windows/amd64', os: 'windows-latest' },
          { name: 'modm8', platform: 'darwin/universal', os: 'macos-latest' }
        ]

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Wails Build
        uses: The-Egg-Corp/wails-build-action@v1
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.22.1'
          node-version: 20
          use-bun: true
          nsis: true
          package: true