name: Crossplatform Build

# on:
#   push:
#     tags:
#       - '*'
on: 
  push:
    tags:
      - "v*.*.*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues.
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'modm8'
            platform:  'windows/amd64'
            os: 'windows-latest'

          - name: 'modm8'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
            
          - name: 'modm8'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Wails Build
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22.1'