name: Verify Configuration
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: "modm8.exe", platform: "windows/amd64", os: "windows-latest" },
          { name: "modm8", platform: "linux/amd64", os: "ubuntu-latest" },
          { name: "modm8", platform: "darwin/universal", os: "macos-latest" }
        ]

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
 
      - name: Verify 'wails.json' file exists.
        shell: bash
        run: |
          if [ ! -f ./wails.json ]; then
            echo -e "\033[31mError: wails.json not found in the root directory!"
            exit 1
          fi

      - name: Read properties.
        shell: bash
        run: |
          PROJ_NAME=$(jq -r '.name' ./wails.json)
            
          if [ -z "$PROJ_NAME" ]; then
            echo -e "\033[31mError: key `name` empty or not found in wails.json!"
            exit 1
          fi

          echo -e "\033[32mProject name is '$PROJ_NAME'"

          OUTPUT_NAME=$(jq -r '.outputfilename' ./wails.json)
            
          if [ -z "$OUTPUT_NAME" ]; then
            echo -e "\033[31mError: key `outputfilename` empty or not found in wails.json!"
            exit 1
          fi
            
          echo -e "\033[32mOutput file (binary) name is '$OUTPUT_NAME'"