name: Upload Artifacts to Draft Release
on: 
  release:
    types: [created]

jobs: 
  upload:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Upload to release
        uses: actions/upload-artifact@v4
        id: build
        with:
          path: ""
